import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import PageTransition from "@/components/PageTransition";
import PageHeader from "@/components/PageHeader";
import CartProvider from "@/context/carContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader/>
        <main className="container max-w-3xl mx-auto mt-4 space-y-4">
          <CartProvider>
            <PageHeader />
            <PageTransition>
              {children}
            </PageTransition>
          </CartProvider>
        </main>
      </body>
    </html>
  );
}
